### ISSUE TITLE
Can't bind to a channel

### ISSUE THREAD

**Issue by Psychocrysma** [WeebDev/Listen.moe-Discord#8]
It is as said. We've been trying to bind this to a voice channel with the ~~join channel for an hour and it won't work.

**Comment by vzwGrey** [comment]
The bot does not stream the radio anymore. That feature has been removed a while ago.
Just use [the website](https://listen.moe/), it has far better quality anyway.

**Comment by Pitu** [comment]
You can also use https://mirai.brussell.me/ to stream the radio if you really want to listen through Discord.
