### ISSUE TITLE
Cannot get bot to join channel

### ISSUE THREAD

**Issue by corvidcrowns** [WeebDev/Listen.moe-Discord#9]
For the past couple of weeks I've been trying to get the bot to work on two different discord servers. It responds to other commands such as ~~np, but when in a voice channel, if ~~join is used, nothing happens. It doesn't join, it doesn't respond to tell us there's an error, nothing. Unfortunately I've tried this with several other people in my servers as well, and all of them have the same results - other commands work, ~~join does not.

**Comment by Pitu** [comment]
The bot doesn't play music anymore, although we are working on new features for it. For the time being, you can use either Mirai or Ayana, or any other bot that plays streams and point it to https://listen.moe/stream, although the previously mentioned ones already have built-in support for LISTEN.moe.
